openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /api/messages:
    get:
      summary: Get all messages
      tags:
        - Messages
      responses:
        200:
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        500:
          description: Internal Server Error

    post:
      summary: Create a new message
      tags:
        - Messages
      requestBody:
        $ref: '#/components/requestBodies/createMessage'
      responses:
        201:
          description: Message created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        400:
          description: Bad Request
        500:
          description: Internal Server Error

  /api/messages/{messageId}:
    get:
      summary: Get a message by its ID
      tags:
        - Messages
      parameters:
        - in: path
          name: messageId
          required: true
          description: ID of the message
          schema:
            type: string
      responses:
        200:
          description: Message retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        500:
          description: Internal Server Error

    put:
      summary: Update a message by its ID
      tags:
        - Messages
      parameters:
        - in: path
          name: messageId
          required: true
          description: ID of the message
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/createMessage'
      responses:
        204:
          description: Message updated successfully
        400:
          description: Bad Request
        500:
          description: Internal Server Error

    delete:
      summary: Delete a message by its ID
      tags:
        - Messages
      parameters:
        - in: path
          name: messageId
          required: true
          description: ID of the message
          schema:
            type: string
      responses:
        204:
          description: Message deleted successfully
        500:
          description: Internal Server Error

components:
  schemas:
    Message:
      type: object
      properties:
        _id:
          type: string
          description: ID of the message
        user:
          type: string
          description: ID of the user
        message:
          type: string
          description: Message content
      example:
        _id: 5f9d4b7b9c9d6b2b1c7d7b7b
        user: 5f9d4b7b9c9d6b2b1c7d7b7b
        message: "Hello, how are you?"

  requestBodies:
    createMessage:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              user:
                type: string
                description: ID of the user
              message:
                type: string
                description: Message content
              required:
                - user
                - message
